### ISSUE TITLE
DjiLiveview_Init return code: 236  

### ISSUE THREAD

**Issue by zj1838277795** [dji-sdk/Payload-SDK#111]
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
读取h264视频流的初始化函数必须在连接无人机的时候才会初始化成功吗

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/87368'>Zendesk ticket #87368</a>:<br><br>PSDK的初始化需要连接无人机。支持PSDK（core）初始化完成，才能去初始化其他的各功能模块。
<br><p><em><small>°°°</small></em></p>
