### ISSUE TITLE
拉流回调函数的执行机制问题

### ISSUE THREAD

**Issue by zj1838277795** [dji-sdk/Payload-SDK#114]
DjiLiveview_StartH264Stream函数的最后一个参数是回调函数用于接收H264流的，如果我在这个回调里加了一个3s的延迟，每次收到的数据都是实时的吗，中间的h264数据应该是抛掉了是吗，正常不加延迟有的non-IDR帧是分2次收到的（我在每次收到数据时加了分隔符发现的），假如我加了3s的延迟会不会出现non-IDR帧的不连续的问题

**Comment by zj1838277795** [comment]
我用官方测试样例试了，好像是psdk做了数据缓冲，数据没有抛掉，加了延迟旧的数据也会返回来

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/88147'>Zendesk ticket #88147</a>:<br><br>PSDK有做缓存，回调函数是实时将数据上抛，如果人为在回调中加延时会阻塞回调，最终还是可能导致数据丢失。
<br><p><em><small>°°°</small></em></p>
