### ISSUE TITLE
使用MDK编译，报错Undefined symbol DjiCameraManager_ResetCameraSettings (referred from test_camera_manager.o)

### ISSUE THREAD

**Issue by 475241512** [dji-sdk/Payload-SDK#126]
在test_camera_manager.c 第 1582行 报错未定义
returnCode = DjiCameraManager_ResetCameraSettings(mountPosition);
在dji_camera_manager.h中有声明
T_DjiReturnCode DjiCameraManager_ResetCameraSettings(E_DjiMountPosition position);

![image](https://github.com/dji-sdk/Payload-SDK/assets/8843501/d834f27e-7c0b-4233-a159-fce90edd8c6c)

编译信息：
Build started: Project: mdk_app
*** Using Compiler 'V5.06 update 7 (build 960)', folder: 'C:\Keil_v5\ARM\ARMCC\Bin'
Build target 'mdk_app'
Note: source file '..\..\..\..\..\module_sample\widget_interaction_test\file_binary_array_list_en.c' - object file renamed from '.\Objects\file_binary_array_list_en.o' to '.\Objects\file_binary_array_list_en_1.o'.
linking...
.\Objects\mdk_app.axf: Error: L6218E: Undefined symbol DjiCameraManager_ResetCameraSettings (referred from test_camera_manager.o).
Not enough information to list image symbols.
Not enough information to list load addresses in the image map.
Finished: 2 information, 0 warning and 1 error messages.
".\Objects\mdk_app.axf" - 1 Error(s), 0 Warning(s).
Target not created.
Build Time Elapsed:  00:00:01

**Comment by dji-dev** [comment]
Agent comment from shiyao.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/93203'>Zendesk ticket #93203</a>:<br><br>尊敬的开发者，

您好，感谢您联系DJI 大疆创新。

很抱歉给您带来不好的体验，关于编译问题，我们已在PSDK3.7中修复了此问题，如果您暂时不需要用到相机部分功能，可以先将这部分注释编译。

感谢您对大疆产品的支持！祝您一切顺利！

Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
