### ISSUE TITLE
使用bootloader跳转，在APP中为何没有重新配置中断向量偏移？

### ISSUE THREAD

**Issue by 475241512** [dji-sdk/Payload-SDK#127]
是需要自己配置还是不需要？源码不改，直接编译下载应该会跑飞吧？

**Comment by 475241512** [comment]
freertos处理

**Comment by dji-dev** [comment]
Agent comment from xiaorong.zheng in <a href='https://djisdksupport.zendesk.com/agent/tickets/93303'>Zendesk ticket #93303</a>:<br><br>freertos需要手动进行配置。
<br><p><em><small>°°°</small></em></p>

**Comment by 475241512** [comment]
谢谢。运行没问题，但是不知道是在freertos中哪里配置中断向量偏移的，以前只是简单粗暴的在初始化前重新映射  - .-
`SCB->VTOR = FLASH_BASE | APPLICATION_ADDRESS;`
MDK - Target - IROM1 - Start  0x8010000
@dji-dev 能否请教一下在什么位置配置，谢谢 :)

**Comment by dji-dev** [comment]
Agent comment from xiaorong.zheng in <a href='https://djisdksupport.zendesk.com/agent/tickets/93303'>Zendesk ticket #93303</a>:<br><br>这个要根据您自己的芯片手册进行配置，网上其实有很多可供参考的资料，这个可能需要您自己学习一下。
<br><p><em><small>°°°</small></em></p>

**Comment by 475241512** [comment]
谢谢！看到了在启动文件中配置了 ：）
