### ISSUE TITLE
使用樹莓派Zero 2 w編釋PSDK 3.6.0

### ISSUE THREAD

**Issue by ghhhgfgh** [dji-sdk/Payload-SDK#129]
使用樹莓派Zero 2 w編釋PSDK 3.6.0時，出現如圖問題
![github報單](https://github.com/dji-sdk/Payload-SDK/assets/44599541/79bfccd5-c1c2-4309-acc4-eca523b2beb0)

平台資訊如圖:
![uname](https://github.com/dji-sdk/Payload-SDK/assets/44599541/2bb73698-0a38-4465-bd4a-7636899d476c)

使用的OS為:Raspberry Pi OS (64-bit)
https://www.raspberrypi.com/software/operating-systems/

**Comment by dji-dev** [comment]
Agent comment from shiyao.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/93668'>Zendesk ticket #93668</a>:<br><br>尊敬的开发者，

您好，感谢您联系DJI 大疆创新。

这个问题是开发者使用的编译器检查要求不同，我们会在PSDK3.7修复这个问题，PSDK3.7近期就会发布，请您耐心等候并留意下发布公告，为您带来的不便，我们深感抱歉！

感谢您对大疆产品的支持！祝您一切顺利！

Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
