### ISSUE TITLE
Update POI via the payload SDK

### ISSUE THREAD

**Issue by Ellislee1** [dji-sdk/Payload-SDK#206]
Is there a way that we can update the Point of Interest, using the payload SKD. We have a M350 and a using the eport for development. We have it setup such that some logic on the payload wants to update the Point of interest so that the drone is always looking at it.

**Comment by dji-dev** [comment]
Agent comment from Leon in <a href='https://djisdksupport.zendesk.com/agent/tickets/118189'>Zendesk ticket #118189</a>:<br><br>Dear Developer,

Hello, thank you for contacting DJI.

We are sorry, but we have confirmed that PSDK does not provide such an interface. Unfortunately, we may not be able to meet your needs.

Thank you for your support of DJI products! Wish you all the best!

Best Regards,
DJI SDK Technical Support
<br><p><em><small>°°°</small></em></p>
