### ISSUE TITLE
使用Pyaload SDK推动实时视频到遥控器

### ISSUE THREAD

**Issue by my-run** [dji-sdk/Payload-SDK#209]

**Comment by dji-dev** [comment]
Agent comment from Leon in <a href='https://djisdksupport.zendesk.com/agent/tickets/118407'>Zendesk ticket #118407</a>:<br><br>尊敬的开发者，

您好，感谢您联系DJI 大疆创新。

请问下过程中您有遇到什么提示或者报错吗？您使用的通道是DJI-H264还是Custom-H264？

感谢您对大疆产品的支持！祝您一切顺利！

Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
