### ISSUE TITLE
aaa

### ISSUE THREAD

**Issue by hummelslei** [dji-sdk/Payload-SDK#4]
tttt gz#23616 gz#23685

**Comment by hummelslei** [comment]
xczxzcz

**Comment by ChrisChen365** [comment]
解决一下啊

**Comment by ChrisChen365** [comment]
> Public comment from 平安 in <a href='https://djisdksupport.zendesk.com/agent/tickets/23685'>Zendesk ticket #23685</a>:<br><br>666666666666666
