### ISSUE TITLE
DJI FPV 

### ISSUE THREAD

**Issue by TomaszWaszczyk** [dji-sdk/Payload-SDK#42]
Hey,

There is any possibilities to use SDK with DJI FPV? Any tutorial?

Appreciate for any answer.
Thanks!

**Comment by daz** [comment]
No. M200, M210, M30, and M300 only. 

https://developer.dji.com/document/5a9c4f53-7bf3-41f0-9cd6-d0eeead6c8d2

**Comment by TomaszWaszczyk** [comment]
Thanks for the answer!
