### ISSUE TITLE
 Length of user information string is beyond limit error

### ISSUE THREAD

**Issue by snakehaihai** [dji-sdk/Payload-SDK#44]
Hi
I`m testing out the PSDKv3 on a NUC with M300 drone. 
After copy everything from developer account to  samples/sample_c/platform/linux/manifold2/application/dji_sdk_app_info.h and compile
this error comes out

Any idea how to solve this? 

![image](https://user-images.githubusercontent.com/6070995/165227940-c30317db-a0db-458a-9db1-52e74c706cb2.png)

**Comment by dji-kyle** [comment]
Please create a new Payload SDK APP info for PSDK, the appkey for PSDK is 32 digit.
Reference:
https://sdk-forum.dji.net/hc/en-us/articles/4408437830041
